# Generated by Django 3.0.1 on 2019-12-27 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('content', models.TextField(max_length=100)),
                ('date', models.DateField()),
                ('pic1', models.ImageField(default=None, upload_to='static/event pics')),
                ('pic2', models.ImageField(default=None, upload_to='static/event pics')),
                ('pic3', models.ImageField(default=None, upload_to='static/event pics')),
                ('status', models.CharField(choices=[(True, 'Upcoming'), (False, 'Happened')], max_length=10)),
            ],
        ),
    ]
