# Generated by Django 3.0.1 on 2019-12-27 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20191228_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='pic1',
            field=models.ImageField(default=None, upload_to='static/event pics'),
        ),
        migrations.AlterField(
            model_name='event',
            name='pic2',
            field=models.ImageField(default=None, upload_to='static/event pics'),
        ),
        migrations.AlterField(
            model_name='event',
            name='pic3',
            field=models.ImageField(default=None, upload_to='static/event pics'),
        ),
    ]
