# Generated by Django 3.0.1 on 2019-12-27 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20191228_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='pic10',
            field=models.ImageField(default=None, upload_to='static/event pics'),
        ),
        migrations.AddField(
            model_name='event',
            name='pic11',
            field=models.ImageField(default=None, upload_to='static/event pics'),
        ),
        migrations.AddField(
            model_name='event',
            name='pic4',
            field=models.ImageField(default=None, upload_to='static/event pics'),
        ),
        migrations.AddField(
            model_name='event',
            name='pic5',
            field=models.ImageField(default=None, upload_to='static/event pics'),
        ),
        migrations.AddField(
            model_name='event',
            name='pic6',
            field=models.ImageField(default=None, upload_to='static/event pics'),
        ),
        migrations.AddField(
            model_name='event',
            name='pic7',
            field=models.ImageField(default=None, upload_to='static/event pics'),
        ),
        migrations.AddField(
            model_name='event',
            name='pic8',
            field=models.ImageField(default=None, upload_to='static/event pics'),
        ),
        migrations.AddField(
            model_name='event',
            name='pic9',
            field=models.ImageField(default=None, upload_to='static/event pics'),
        ),
    ]
