# Generated by Django 3.0.1 on 2020-02-01 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_event_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='venue',
        ),
    ]
