# Generated by Django 3.0.1 on 2020-02-15 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20200205_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='certi_description',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
