# Generated by Django 3.0.1 on 2019-12-27 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20191228_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='pic1',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='static/event pics'),
        ),
        migrations.AlterField(
            model_name='event',
            name='pic10',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='static/event pics'),
        ),
        migrations.AlterField(
            model_name='event',
            name='pic11',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='static/event pics'),
        ),
        migrations.AlterField(
            model_name='event',
            name='pic2',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='static/event pics'),
        ),
        migrations.AlterField(
            model_name='event',
            name='pic3',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='static/event pics'),
        ),
        migrations.AlterField(
            model_name='event',
            name='pic4',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='static/event pics'),
        ),
        migrations.AlterField(
            model_name='event',
            name='pic5',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='static/event pics'),
        ),
        migrations.AlterField(
            model_name='event',
            name='pic6',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='static/event pics'),
        ),
        migrations.AlterField(
            model_name='event',
            name='pic7',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='static/event pics'),
        ),
        migrations.AlterField(
            model_name='event',
            name='pic8',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='static/event pics'),
        ),
        migrations.AlterField(
            model_name='event',
            name='pic9',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='static/event pics'),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('True', 'Upcoming'), ('False', 'Happened')], max_length=10),
        ),
    ]
