# Generated by Django 3.0.1 on 2020-04-23 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20200217_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='pic1',
            field=models.ImageField(default=None, upload_to='event pics'),
        ),
    ]
