# Generated by Django 3.0.1 on 2020-01-01 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0007_auto_20191230_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='pic1',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='event pics'),
        ),
        migrations.AlterField(
            model_name='event',
            name='pic10',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='event pics'),
        ),
        migrations.AlterField(
            model_name='event',
            name='pic11',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='event pics'),
        ),
        migrations.AlterField(
            model_name='event',
            name='pic2',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='event pics'),
        ),
        migrations.AlterField(
            model_name='event',
            name='pic3',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='event pics'),
        ),
        migrations.AlterField(
            model_name='event',
            name='pic4',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='event pics'),
        ),
        migrations.AlterField(
            model_name='event',
            name='pic5',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='event pics'),
        ),
        migrations.AlterField(
            model_name='event',
            name='pic6',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='event pics'),
        ),
        migrations.AlterField(
            model_name='event',
            name='pic7',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='event pics'),
        ),
        migrations.AlterField(
            model_name='event',
            name='pic8',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='event pics'),
        ),
        migrations.AlterField(
            model_name='event',
            name='pic9',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='event pics'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='registrations'),
        ),
        migrations.CreateModel(
            name='RequestedEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
