# Generated by Django 3.0.5 on 2020-04-26 03:05

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20200423_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute', models.CharField(max_length=100)),
                ('previous_events', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=1000, null=True)),
                ('contact_person_phone_number', models.BigIntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, default=None, max_length=100, null=True)),
            ],
            options={
                'ordering': ['institute'],
            },
        ),
    ]
