# Generated by Django 3.0.1 on 2020-02-05 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slideshowpic',
            options={'ordering': ['number']},
        ),
        migrations.AddField(
            model_name='slideshowpic',
            name='number',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='query',
            field=models.TextField(max_length=5000),
        ),
    ]
