# Generated by Django 3.0.1 on 2020-01-05 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200103_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='slideshowpic',
            name='title',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
