# Generated by Django 3.0.1 on 2020-02-05 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200205_1639'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['description']},
        ),
        migrations.AddField(
            model_name='member',
            name='status',
            field=models.CharField(blank=True, choices=[('True', 'Current'), ('False', 'Alumni')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='description',
            field=models.CharField(choices=[('1', 'Student Co-ordinator'), ('2', 'Member'), ('3', 'Ex Student Co-ordinator'), ('4', 'Ex Member')], max_length=100),
        ),
    ]
