# Generated by Django 3.0.1 on 2020-02-05 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200205_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='description',
            field=models.CharField(choices=[('Student Co-ordinator', '1'), ('Member', '2'), ('Ex Student Co-ordinator', '3'), ('Ex Member', '4')], max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.CharField(blank=True, choices=[('Current', 'Current'), ('Alumni', 'Alumni')], max_length=100, null=True),
        ),
    ]
