# Generated by Django 3.0.1 on 2020-01-05 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200105_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='query',
            field=models.TextField(max_length=2000),
        ),
    ]
