# Generated by Django 3.0.1 on 2020-02-05 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200205_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='description',
            field=models.CharField(choices=[('Student Co-ordinator', '1-Student Co-ordinator'), ('Member', '2-Member'), ('Ex Student Co-ordinator', '3-Ex Student Co-ordinator'), ('Ex Member', '4-Ex Member')], max_length=100),
        ),
    ]
