# Generated by Django 3.0.1 on 2020-02-05 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200205_1859'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['-description']},
        ),
    ]
