# Generated by Django 3.0.1 on 2020-01-05 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_password2'),
        ('core', '0007_auto_20200105_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='userprofile',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile'),
        ),
    ]
