# Generated by Django 2.2.10 on 2020-12-24 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200501_0045'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.BigIntegerField()),
                ('roll_no', models.BigIntegerField()),
                ('wa_no', models.BigIntegerField()),
                ('hobbies', models.TextField()),
                ('skills', models.CharField(max_length=1000)),
                ('course', models.CharField(max_length=1000)),
                ('branch', models.CharField(max_length=1000)),
                ('reason', models.TextField()),
            ],
        ),
    ]
