# Generated by Django 2.2.10 on 2020-12-24 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auditions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditions',
            name='wa_no',
        ),
    ]
