# Generated by Django 3.0.1 on 2019-12-27 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.IntegerField(unique=True)),
                ('branch', models.CharField(choices=[('CE', 'CE'), ('IT', 'IT'), ('ECE', 'ECE'), ('ECS', 'ECS'), ('EIC', 'EIC'), ('EL', 'EL'), ('MECH', 'MECH'), ('CIVIL', 'CIVIL')], max_length=10)),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
