# Generated by Django 3.0.1 on 2019-12-27 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='icard',
            field=models.ImageField(default=None, upload_to='static/icard'),
        ),
    ]
