# Generated by Django 3.0.1 on 2019-12-27 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_icard'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phoneno',
            field=models.IntegerField(default=None, unique=True),
        ),
    ]
