# Generated by Django 3.0.1 on 2019-12-27 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_phoneno'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
