# Generated by Django 3.0.1 on 2019-12-27 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='icard',
            field=models.ImageField(blank=True, null=True, upload_to='static/icard'),
        ),
    ]
