# Generated by Django 3.0.1 on 2020-01-05 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_password2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facultyprofile',
            old_name='description',
            new_name='department',
        ),
        migrations.RemoveField(
            model_name='facultyprofile',
            name='name',
        ),
        migrations.AlterField(
            model_name='facultyprofile',
            name='pic',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='faculty pics'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='pic',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='student pics'),
        ),
    ]
