# Generated by Django 3.0.1 on 2020-01-18 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200105_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='pic',
            field=models.ImageField(blank=True, default='student pics/default_user.png', null=True, upload_to='student pics'),
        ),
    ]
