# Generated by Django 3.0.1 on 2020-02-05 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200118_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='course',
            field=models.CharField(choices=[('BTECH', 'Btech'), ('MTECH', 'Mtech'), ('BCA', 'BCA'), ('MCA', 'MCA'), ('BSC', 'Bsc'), ('MSC', 'Msc'), ('MBA', 'MBA')], max_length=10),
        ),
    ]
