# Generated by Django 3.0.1 on 2020-02-05 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200205_1629'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facultyprofile',
            options={'ordering': ['-position']},
        ),
        migrations.AlterField(
            model_name='facultyprofile',
            name='position',
            field=models.CharField(choices=[('Head', '1-Head'), ('Member', '2-Member')], max_length=20),
        ),
    ]
