# Generated by Django 3.0.1 on 2019-12-27 23:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0009_profile_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.IntegerField(unique=True)),
                ('course', models.CharField(choices=[('BTECH', 'Btech'), ('MTECH', 'Mtech'), ('BCA', 'BCA'), ('MCA', 'MCA'), ('BSC', 'Bsc'), ('MSC', 'Msc'), ('MBA', 'MBA')], default='CE', max_length=10)),
                ('branch', models.CharField(choices=[('CE', 'CE'), ('IT', 'IT'), ('ECE', 'ECE'), ('ECS', 'ECS'), ('EIC', 'EIC'), ('EL', 'EL'), ('MECH', 'MECH'), ('CIVIL', 'CIVIL')], max_length=10)),
                ('icard', models.ImageField(blank=True, null=True, upload_to='static/icard')),
                ('phoneno', models.IntegerField(default=None, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
