# Generated by Django 3.0.1 on 2020-01-01 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20191228_0456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='icard',
            field=models.ImageField(blank=True, null=True, upload_to='icard'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phoneno',
            field=models.IntegerField(default=None, max_length=9999999999),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='roll_no',
            field=models.IntegerField(max_length=99999999999, unique=True),
        ),
    ]
