# Generated by Django 3.0.1 on 2020-02-16 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20200215_1627'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['-roll_no', 'branch', 'course']},
        ),
    ]
