# Generated by Django 3.0.5 on 2020-04-25 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20200216_2348'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facultyprofile',
            options={'ordering': ['position']},
        ),
    ]
