# Generated by Django 3.0.1 on 2020-05-21 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20200425_0710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='password2',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='branch',
            field=models.CharField(choices=[('CE', 'CE'), ('IT', 'IT'), ('ECE', 'ECE'), ('ECS', 'ECS'), ('EIC', 'EIC'), ('EL', 'EL'), ('MECH', 'MECH'), ('CIVIL', 'CIVIL'), ('Mathematics', 'Mathematics'), ('Chemistry', 'Chemistry'), ('Physics', 'Physics'), ('Animation', 'Animation'), ('Others', 'Others')], max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='course',
            field=models.CharField(choices=[('BTECH', 'Btech'), ('MTECH', 'Mtech'), ('BCA', 'BCA'), ('MCA', 'MCA'), ('BSC', 'Bsc'), ('MSC', 'Msc'), ('MBA', 'MBA'), ('BBA', 'BBA')], max_length=50),
        ),
    ]
