# Generated by Django 3.0.1 on 2019-12-23 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191222_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=100)),
                ('edescription', models.CharField(max_length=500)),
                ('econtent', models.TextField(max_length=100)),
                ('date', models.DateField()),
                ('pic', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
