# Generated by Django 3.0.1 on 2019-12-27 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20191223_2103'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
