# Generated by Django 3.0.1 on 2019-12-30 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20191228_0153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='pic1',
            field=models.ImageField(default=None, upload_to='blog pics'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pic2',
            field=models.ImageField(default=None, upload_to='blog pics'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pic3',
            field=models.ImageField(default=None, upload_to='blog pics'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pic4',
            field=models.ImageField(default=None, upload_to='blog pics'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pic5',
            field=models.ImageField(default=None, upload_to='blog pics'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_author', models.CharField(max_length=50)),
                ('comment_content', models.CharField(max_length=200)),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.Post')),
            ],
            options={
                'ordering': ['-comment_date'],
            },
        ),
    ]
