# Generated by Django 3.0.1 on 2019-12-30 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20191230_1740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_author',
            new_name='comment_user',
        ),
    ]
