# Generated by Django 3.0.1 on 2019-12-30 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20191230_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pic1',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='blog pics'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pic2',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='blog pics'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pic3',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='blog pics'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pic4',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='blog pics'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pic5',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='blog pics'),
        ),
    ]
